spring:
    datasource:
        url: jdbc:mysql://localhost:3306/spring_security
        username: root
        password:

        testWhileIdle: true
        validationQuery: SELECT 1

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect

logging:
    level.: ERROR
    com.thoughtworks: DEBUG
